site_name: sv-dlp documentation

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
- search
- mkdocstrings

nav:
  - "Index": index.md
  - "Module - Getting Started": module_basics.md
  - "Downloading Process": downloading_process.md
  - "Command Line Interface - User Guide": cli_guide.md
  - "Class Documentation": class_documentation.md