site_name: sv-dlp documentation
repo_name: juanpisss/sv-dlp
repo_url: https://github.com/juanpisss/sv-dlp

nav:
  - "Index":                                    index.md
  - "Module - Basics & Getting Started":        module_basics.md
  - "Command Line Interface - User Guide":      cli_guide.md
  - "Supported Services":                       supported_services.md
  - "Contributing - Basics & Getting Started":  contributing_services.md
  - "Class Documentation":                      class_documentation.md

theme:
  name: "material"
  palette:
    # Dark Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light green
      toggle:
        icon: material/eye
        name: Dark Mode
        
    # Light Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/eye-outline
        name: Switch to light mode

plugins:
- search
- mkdocstrings
- include-markdown
- mike

extra:
  version:
    provider: mike
