site_name: sv-dlp documentation

repo_name: juanpisss/sv-dlp
repo_url: https://github.com/juanpisss/sv-dlp

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
- search
- mkdocstrings
- include-markdown

nav:
  - "Index": index.md
  - "Module - Basics & Getting Started":        module_basics.md
  - "Command Line Interface - User Guide":      cli_guide.md
  - "Supported Services":                       supported_services.md
  - "Contributing - Basics & Getting Started":  contributing_services.md
  - "Class Documentation":                      class_documentation.md
