name: Compile & Ship

on:
  workflow_dispatch:
    inputs:
      pre_release:
        type: boolean
        description: Nightly Build
        required: false

jobs:
  publish-release:
    name: "Create Release"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump_version.outputs.ytdlp_version }}
      upload_url: ${{ steps.release.outputs.upload_url }}

    steps:
    - name: Switch Branch
      uses: actions/checkout@v2
      with:
        ref: 'master'

    - name: Generate Version
      id: ver
      run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

    - name: Get Changelog
      id: release_changelog
      run: sed '1,/## '$ver'/d;/'---'/Q' CHANGELOG.md

    - name: Create Release
      id: release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.ver.outputs.ver }}
        release_name: ${{ steps.ver.outputs.ver }}
        body_path: ${{ steps.release_changelog.outputs.release_changelog }}
        draft: false
        prerelease: ${{ github.event.inputs.pre_release }}

  compile-linux_amd64:
      name: "Compile Linux AMD64"
      runs-on: ubuntu-latest
      needs: publish-release

      steps:
      - name: Switch Branch
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Set up Python 3.10.2
        uses: actions/setup-python@v2
        with:
            python-version: '3.10.2'
            architecture: 'x64'

      - name: Install Required Modules
        run: python -m pip install -r requirements.txt

      - name: Build - Linux x64 Binary
        run: python build.py

      - name: Upload - Linux x64 Binary
        id: upload-linux_amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish-release.release.outputs.upload_url }}
          asset_path: ./dist/sv-dlp
          asset_name: sv-dlp
          asset_content_type: application/tar+gzip

  compile-win_64:
      name: "Compile Windows x64"
      runs-on: windows-latest
      needs: publish-release

      steps:
      - name: Switch Branch
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Set up Python 3.10.2
        uses: actions/setup-python@v2
        with:
            python-version: '3.10.2'
            architecture: 'x64'

      - name: Install Required Modules
        run: python -m pip install -r requirements.txt

      - name: Build - Windows x64 Binary
        run: python build.py

      - name: Upload - Windows x64 Binary
        id: upload-win_amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish-release.release.outputs.upload_url }}
          asset_path: ./dist/sv-dlp.exe
          asset_name: sv-dlp.exe
          asset_content_type: application/tar+gzip

  compile-win_x86:
      name: "Compile Windows x86"
      runs-on: windows-latest
      needs: publish-release

      steps:
      - name: Switch Branch
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Set up Python 3.10.2
        uses: actions/setup-python@v2
        with:
            python-version: '3.10.2'
            architecture: 'x86'

      - name: Install Required Modules
        run: python -m pip install -r requirements.txt

      - name: Build - Windows x86 Binary
        run: python build.py

      - name: Upload - Windows x86 Binary
        id: upload-win_x86
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish-release.release.outputs.upload_url }}
          asset_path: ./dist/sv-dlp_x86.exe
          asset_name: sv-dlp_x86.exe
          asset_content_type: application/tar+gzip

  compile-darwin:
      name: "Compile macOS"
      runs-on: macos-latest
      needs: publish-release

      steps:
      - name: Switch Branch
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Set up Python 3.10.2
        uses: actions/setup-python@v2
        with:
            python-version: '3.10.2'
            architecture: 'x64'

      - name: Install Required Modules
        run: python -m pip install -r requirements.txt

      - name: Build - macOS Binary
        run: python build.py

      - name: Upload - macOS Binary
        id: upload-darwin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish-release.release.outputs.upload_url }}
          asset_path: ./dist/sv-dlp_macos
          asset_name: sv-dlp_macos
          asset_content_type: application/tar+gzip