name: Dry Build

on:
  push:

jobs:
  create-release:
    name: "Preparations"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.sv-dlp_version }}

    steps:
      - name: Switch Branch
        uses: actions/checkout@v2

      - name: Bump version
        id: version
        run: python utils/version.py

      - name: Get Changelog
        run: sed '/## '${{ steps.version.outputs.sv-dlp_version }}'/d;/'---'/Q' CHANGELOG.md >> changelog_body

      - name: Remove changelog_body
        run: rm changelog_body

  build-publish-pypi:
    name: "Build & Publish to PyPi"
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.10]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cibuildwheel

      - name: Build Binaries
        run: |
          python build_cli.py

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Publish to PyPI
        run: |
          ls wheelhouse
        # uses: pypa/gh-action-pypi-publish@release/v1
        # with:
        #   password: ${{ secrets.PYPI_API_TOKEN }}
