name: Dry Build

on:
  push:

jobs:
  create-release:
    name: "Preparations"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.sv-dlp_version }}
      # upload_url: ${{ steps.release.outputs.upload_url }}
      # id: ${{ steps.release.outputs.id }}
      # version: ${{ steps.version.outputs.sv-dlp_version }}

    steps:
      - name: Switch Branch
        uses: actions/checkout@v2

      - name: Bump version
        id: version
        run: python utils/version.py

      - name: Get Changelog
        run: sed '/## '${{ steps.version.outputs.sv-dlp_version }}'/d;/'---'/Q' CHANGELOG.md >> changelog_body

      - name: Remove changelog_body
        run: rm changelog_body

  build-publish-pypi:
    name: "Build & Publish to PyPi"
    needs: create-release
    runs-on: ubuntu-latest

    steps:
      - name: Switch Branch
        uses: actions/checkout@v2
        with:
          ref: "master"

      - name: Set up Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.5"
          architecture: "x64"

      - name: Build Package
        run: |
          python -m pip install setuptools wheel
          python setup.py sdist bdist_wheel

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist/*

  compile:
    name: "Compile"
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_path: "./dist/bin/sv-dlp"
            asset_name: "sv-dlp"
            asset_content_type: "application/tar+gzip"
            system_libs: true
          - os: windows-latest
            asset_path: "./dist/bin/sv-dlp.exe"
            asset_name: "sv-dlp.exe"
            asset_content_type: "application/tar+gzip"
            system_libs: false
          - os: macos-latest
            asset_path: "./dist/bin/sv-dlp_macos"
            asset_name: "sv-dlp_macos"
            asset_content_type: "application/tar+gzip"
            system_libs: false

    steps:
      - name: Switch Branch
        uses: actions/checkout@v2

      - name: Set up Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.5"
          architecture: "x64"

      - name: Install Required Modules
        run: python -m pip install -r requirements.txt

      - name: Install System Libraries
        if: matrix.system_libs
        run: sudo apt-get install libde265-0 liblzma5 libjpeg8 libjpeg9 libxau6 libnghttp2-14 libsqlite3-0 libtiff5 python3-libtiff libcurl4 python3-pycurl

      - name: Build Binary
        run: python build_cli.py

      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_path }}

  publish:
    name: Publish Release
    needs: [create-release, build-publish-pypi, compile]
    runs-on: ubuntu-latest
    steps:
      - name: Publish to GitHub
        run: echo pretend this is setting the release to public"
