name: Build & Test

on: [push]

jobs:
  Test:
    name: "Build & Test"
    runs-on: ubuntu-latest

    steps:
    - name: Switch Branch
      uses: actions/checkout@v2
      with:
        ref: 'master'

    - name: Set up Python 3.10.5
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.5'
        architecture: 'x64'

    - name: Install Required Modules
      run: |
        python -m pip install setuptools wheel
        python -m pip install -r requirements.txt

    - name: Build & Install
      run: |
        python setup.py sdist bdist_wheel
        python setup.py install

    - name: Test
      run: |
        python dev_scripts/test.py
